### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://extensions.typo3.org/wsdl/tx_ter_wsdl.php

### ISSUE THREAD

**Issue by DirkPersky** [helhum/ter-client#14]
```
SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://extensions.typo3.org/  
  wsdl/tx_ter_wsdl.php' : failed to load external entity "https://extensions.  
  typo3.org/wsdl/tx_ter_wsdl.php" 

```

You know how i can fix this?

**Comment by helhum** [comment]
since I haven't changed anything in this library for years, the issue you are seeing must be related to the end point not being available. Maybe ask typo3.org maintainers about what if there are issues with the soap service.
