### ISSUE TITLE
Allow line breaks in upload comments

### ISSUE THREAD

**Issue by schams-net** [helhum/ter-client#2]
I am trying to use line breaks in the comment argument when uploading an extension to TER via command line:
```
./ter-client upload extensionkey /tmp/extension -u username -p password \
  -m "Line 1\nLine 2"
```
The upload works fine, but the field in TER shows `\n` as a character:

![screenshot0001](https://user-images.githubusercontent.com/3617721/38019815-5dd2649e-32c4-11e8-8b27-08c252c721c4.png)

Line breaks in the upload form at https://extensions.typo3.org are supported, so I wonder if I am doing something wrong or if `ter-client` does not support this. If the latter, it would be a nice enhancement :-)

**Comment by helhum** [comment]
That is actually not an issue of this package, but an issue with your expectation how the shell works. The ter-client happily accepts new lines, if you pass them with your shell.

Bash:
```
$ echo "foo\nbar"
foo\nbar
```

```
$ echo -e "foo\nbar"
foo
bar
```

Here is an [answer](https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line) how you can solve it with commit messages in git.

Same can be applied for ter-client.

See https://extensions.typo3.org/extension/typo3_console/ which is uploaded with ter-client as well.
