### ISSUE TITLE
Compatibility with PHP 7.2 and 7.3

### ISSUE THREAD

**Issue by garbast** [helhum/ter-client#4]
Could the "php": ">5.3.3 < 7.2" be increased to < 7.4 or is there a reason to keep it below 7.2?

**Comment by garbast** [comment]
Additional information why this is needed. If you want to use ter-client for a release that is TYPO3 9.5 compatible only you get a result like this: https://travis-ci.org/evoWeb/recaptcha/jobs/485132228

Either the packages can not be installed if you select php 7.2 or if you select 7.1 the error is

  Problem 1
    - typo3/cms-core v9.5.4 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.
    - typo3/cms-core v9.5.3 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.
    - typo3/cms-core v9.5.2 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.
    - typo3/cms-core v9.5.1 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.
    - typo3/cms-core v9.5.0 requires php ^7.2 -> your PHP version (7.1.11) does not satisfy that requirement.
    - Installation request for typo3/cms-core ^9.5 -> satisfiable by typo3/cms-core[v9.5.0, v9.5.1, v9.5.2, v9.5.3, v9.5.4].

**Comment by helhum** [comment]
@garbast there is no particular reason for not being marked as compatible with PHP > 7.1

As workaround you could install the [ter client globally](https://github.com/TYPO3-Console/TYPO3-Console/blob/2ba91182cb902e1a464ddeb5a9e7a66afa607322/.travis.yml#L129) instead of as dep to your package that you want to release

**Comment by garbast** [comment]
Thanks for the hint. I'll try that.

**Comment by helhum** [comment]
Should be fixed nontheless here
