### ISSUE TITLE
Allow symfony/console ^4

### ISSUE THREAD

**Issue by tomasnorre** [helhum/ter-client#7]
I wanted to install  helhum/ter-client but have a composer conflict, due to other installed global packages. 

The problem is with the symfony/console requirement, would it be possible to also allow symfony/console ^4 as requirement here?

Then my problem would be solved for now.

I would be happy to test and make a PR. 

Let me know what you think.

**Comment by helhum** [comment]
I think this would be totally fine. just add ^4 as additional dep

**Comment by tomasnorre** [comment]
Super, will do some testing before and submit a PR.

**Comment by tomasnorre** [comment]
I breaks PHP 5.5 compatibility which I personally don't find that bad..  If people are still using that PHP version, they can use and older version of the ter-client.

**Comment by oliverklee** [comment]
AFAICT, this change is not the cause of the breakage. The `.travis.yml` needs to have `dist: trusty` for that: https://github.com/MyIntervals/emogrifier/commit/015bda50739c9a3ff28989ea44baea0f185c7e4f#diff-354f30a63fb0907d4ad57269548329e3

**Comment by tomasnorre** [comment]
Thanks @oliverklee,
That was the issue.. I've created a new PR as I didn't want to amend my commit and I had my commit in master in my fork.

Thanks for pointing this out.
